//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassSchedule2._0.Models.ScheduleDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Students = new HashSet<Member>();
        }
    
        public int Id { get; set; }
        public int ProfessorId { get; set; }
        public int CourseId { get; set; }
        public System.DateTime StarDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan StarTime { get; set; }
        public int Length { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Member Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Students { get; set; }
    }
}
