using System;

namespace CodingPract
{
    class Program
    {
        static void Main(string[] args)
        {
            #region If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
            //int sum = 0;

            //for (int i = 1; i < 1000; i++)
            //{
            //    if (i%5 == 0)
            //    {
            //        sum += i;
            //    }
            //    else if (i%3 == 0)
            //    {
            //        sum += i;
            //    }
            //}

            //Console.WriteLine(sum);
            #endregion

            #region Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...] By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            int sum = 0;
            int max = 4000000;
            for (int n = 0; n < max; n++)
            {
                //only sum the even numbers
                if (second % 2 == 0) sum += second;

                //adjust
                int result = first + second;
                first = second;
                second = result;

                //test for numbers greater than max
                if (result > max) break;
            }

            //output
            Console.WriteLine(sum);
            #endregion
        }
    }
}
