Vagrant.configure("2") do |co|
  # box configuration.
  co.vm.box = "ubuntu/xenial64"
  co.vm.box_version = "20170919.0.0"
  co.vm.box_check_update = false

  # network configuration.
  co.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"

  # provider configuration.
  co.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  # provision configuration.
  co.vm.provision "shell" do |sh|
    sh.path = "Vagrantup.sh"
  end
end
